[[custom_groups]]
name = "🚀 节点选择"
type = "select"
rule = ["[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]DIRECT"]

[[custom_groups]]
name = "📢 谷歌"
type = "select"
rule = ["[]🚀 节点选择","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]🚀 手动切换"]

[[custom_groups]]
name = "🎥 奈飞视频"
type = "select"
rule = ["[]🚀 节点选择","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]🚀 手动切换"]

[[custom_groups]]
name = "📺 巴哈姆特"
type = "select"
rule = ["[]🇨🇳 台湾节点","[]🚀 节点选择","[]🚀 手动切换","[]DIRECT"]

[[custom_groups]]
name = "📺 哔哩哔哩"
type = "select"
rule = ["[]DIRECT","[]🇨🇳 台湾节点","[]🇭🇰 香港节点"]

[[custom_groups]]
name = "🌍 国外媒体"
type = "select"
rule = ["[]🚀 节点选择","[]🚀 手动切换","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点"]

[[custom_groups]]
name = "💬 OpenAi"
type = "select"
rule = ["[]🚀 节点选择","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点","[]🚀 手动切换"]

[[custom_groups]]
name = "Ⓜ️ 微软Bing"
type = "select"
rule = ["[]DIRECT","[]🚀 节点选择","[]🚀 手动切换","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点"]

[[custom_groups]]
name = "Ⓜ️ 微软云盘"
type = "select"
rule = ["[]DIRECT","[]🚀 节点选择","[]🚀 手动切换","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点"]

[[custom_groups]]
name = "Ⓜ️ 微软服务"
type = "select"
rule = ["[]DIRECT","[]🚀 节点选择","[]🚀 手动切换","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点"]

[[custom_groups]]
name = "🎮 游戏平台"
type = "select"
rule = ["[]DIRECT","[]🚀 节点选择","[]🚀 手动切换","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点"]

[[custom_groups]]
name = "🚀 手动切换"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "🐟 漏网之鱼"
type = "select"
rule = ["[]🚀 节点选择","[]🚀 手动切换","[]DIRECT","[]🇭🇰 香港节点","[]🇨🇳 台湾节点","[]🇯🇵 日本节点","[]🇰🇷 韩国节点","[]🇸🇬 新加坡节点","[]🇺🇲 美国节点","[]🇨🇦 加拿大节点"]
