[[custom_groups]]
name = "🇭🇰 香港节点"
type = "url-test"
rule = ["(香?港|HK|Hong Kong)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 60

[[custom_groups]]
name = "🇨🇳 台湾节点"
type = "url-test"
rule = ["(台湾?|新北|彰化|TW|Taiwan)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 60

[[custom_groups]]
name = "🇯🇵 日本节点"
type = "url-test"
rule = ["(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100

[[custom_groups]]
name = "🇰🇷 韩国节点"
type = "url-test"
rule = ["(KR|Korea|KOR|首尔|韩|韓)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100

[[custom_groups]]
name = "🇸🇬 新加坡节点"
type = "url-test"
rule = ["((新加)?坡|狮城|SG|Singapore)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100

[[custom_groups]]
name = "🇺🇲 美国节点"
type = "url-test"
rule = ["(美国?|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|United States)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100

[[custom_groups]]
name = "🇨🇦 加拿大节点"
type = "url-test"
rule = ["(加?拿大|CA|Canada)"]
url = "http://www.gstatic.com/generate_204"
interval = 150
timeout = 3
tolerance = 100
