version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true

#include_remarks = []
exclude_remarks = ["(到期|剩余流量|时间|官网|产品|平台|导航|订阅)"]

clash_rule_base = "https://raw.githubusercontent.com/blzadx/subConvert/main/base/clash_gatewayDev.yml"

# Options for adding emojis
#add_emoji = true
#remove_old_emoji = true

[[custom_groups]]
import = "https://raw.githubusercontent.com/blzadx/subConvert/main/snippets/groups_region.toml"
[[custom_groups]]
import = "https://raw.githubusercontent.com/blzadx/subConvert/main/snippets/groups_rule.toml"

# [[rulesets]]
# import = "https://raw.githubusercontent.com/blzadx/subConvert/main/snippets/personal_rules.txt"
[[rulesets]]
import = "https://raw.githubusercontent.com/blzadx/subConvert/main/snippets/rulesets.toml"

# [[template_args]]
# key = "clash.dns.port"
# value = "5353"