custom:
  enable_rule_generator: true
  overwrite_original_rules: true

  clash_rule_base: "https://raw.githubusercontent.com/blzadx/subConvert/main/base/clash_gatewayDev.yml"
#  surge_rule_base: base/surge.conf
#  surfboard_rule_base: base/surfboard.conf
#  mellow_rule_base: base/mellow.conf
#  quan_rule_base: base/quan.conf
#  quanx_rule_base: base/quanx.conf
#  loon_rule_base: base/loon.conf
#  sssub_rule_base: base/shadowsocks_base.json
#  singbox_rule_base: base/singbox.json

#  rename_node:
#  - {import: snippet/rename.txt}

#  add_emoji: true
#  remove_old_emoji: true
#  emojis:
#  - {import: snippets/emoji.txt}

#  include_remarks: []
  exclude_remarks: ["(到期|剩余流量|时间|官网|产品|平台|导航|订阅)"]
#  template_args:
#  - {key: clash.dns.port, value: 5353}

  proxy_groups:
  - {import: "https://raw.githubusercontent.com/blzadx/subConvert/main/snippets/groups.txt"}

  rulesets:
  - {import: "https://raw.githubusercontent.com/blzadx/subConvert/main/snippets/personal_rules.txt"}
  - {import: "https://raw.githubusercontent.com/blzadx/subConvert/main/snippets/rulesets.txt"}